# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import print_pb2 as print__pb2


class PrinterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PrintPage = channel.unary_unary(
        '/Printer/PrintPage',
        request_serializer=print__pb2.PrintRequest.SerializeToString,
        response_deserializer=print__pb2.PrintResponse.FromString,
        )


class PrinterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PrintPage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrinterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PrintPage': grpc.unary_unary_rpc_method_handler(
          servicer.PrintPage,
          request_deserializer=print__pb2.PrintRequest.FromString,
          response_serializer=print__pb2.PrintResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Printer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
