# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import resume_pb2 as resume__pb2


class ResumeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResume = channel.unary_unary(
                '/Resume/GenerateResume',
                request_serializer=resume__pb2.ResumeRequest.SerializeToString,
                response_deserializer=resume__pb2.ResumeResponse.FromString,
                )


class ResumeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResumeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResume': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResume,
                    request_deserializer=resume__pb2.ResumeRequest.FromString,
                    response_serializer=resume__pb2.ResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Resume', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Resume(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Resume/GenerateResume',
            resume__pb2.ResumeRequest.SerializeToString,
            resume__pb2.ResumeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
