# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import led_sign_pb2 as led__sign__pb2


class LedSignStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HealthCheck = channel.unary_unary(
        '/LedSign/HealthCheck',
        request_serializer=led__sign__pb2.LedSignMessage.SerializeToString,
        response_deserializer=led__sign__pb2.HealthCheckResponse.FromString,
        )
    self.AddMessageToQueue = channel.unary_unary(
        '/LedSign/AddMessageToQueue',
        request_serializer=led__sign__pb2.LedSignRecord.SerializeToString,
        response_deserializer=led__sign__pb2.LedSignMessage.FromString,
        )
    self.ClearMessageQueue = channel.unary_unary(
        '/LedSign/ClearMessageQueue',
        request_serializer=led__sign__pb2.LedSignMessage.SerializeToString,
        response_deserializer=led__sign__pb2.LedSignMessage.FromString,
        )
    self.DeleteMessageFromQueue = channel.unary_unary(
        '/LedSign/DeleteMessageFromQueue',
        request_serializer=led__sign__pb2.LedSignMessage.SerializeToString,
        response_deserializer=led__sign__pb2.LedSignMessage.FromString,
        )


class LedSignServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def HealthCheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddMessageToQueue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearMessageQueue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteMessageFromQueue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LedSignServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=led__sign__pb2.LedSignMessage.FromString,
          response_serializer=led__sign__pb2.HealthCheckResponse.SerializeToString,
      ),
      'AddMessageToQueue': grpc.unary_unary_rpc_method_handler(
          servicer.AddMessageToQueue,
          request_deserializer=led__sign__pb2.LedSignRecord.FromString,
          response_serializer=led__sign__pb2.LedSignMessage.SerializeToString,
      ),
      'ClearMessageQueue': grpc.unary_unary_rpc_method_handler(
          servicer.ClearMessageQueue,
          request_deserializer=led__sign__pb2.LedSignMessage.FromString,
          response_serializer=led__sign__pb2.LedSignMessage.SerializeToString,
      ),
      'DeleteMessageFromQueue': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteMessageFromQueue,
          request_deserializer=led__sign__pb2.LedSignMessage.FromString,
          response_serializer=led__sign__pb2.LedSignMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'LedSign', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
