# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: print_3d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='print_3d.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eprint_3d.proto\"h\n\x0cPrintRequest\x12\x13\n\x0bmember_name\x18\x01 \x01(\t\x12\x1d\n\x15print_volume_cubic_cm\x18\x02 \x01(\r\x12\x0e\n\x06\x63opies\x18\x03 \x01(\r\x12\x14\n\x0c\x65ncoded_file\x18\x04 \x01(\x0c\" \n\rPrintResponse\x12\x0f\n\x07message\x18\x01 \x01(\t23\n\tPrinter3D\x12&\n\x05Print\x12\r.PrintRequest\x1a\x0e.PrintResponseb\x06proto3')
)




_PRINTREQUEST = _descriptor.Descriptor(
  name='PrintRequest',
  full_name='PrintRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='member_name', full_name='PrintRequest.member_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='print_volume_cubic_cm', full_name='PrintRequest.print_volume_cubic_cm', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='copies', full_name='PrintRequest.copies', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoded_file', full_name='PrintRequest.encoded_file', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=122,
)


_PRINTRESPONSE = _descriptor.Descriptor(
  name='PrintResponse',
  full_name='PrintResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='PrintResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['PrintRequest'] = _PRINTREQUEST
DESCRIPTOR.message_types_by_name['PrintResponse'] = _PRINTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrintRequest = _reflection.GeneratedProtocolMessageType('PrintRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRINTREQUEST,
  '__module__' : 'print_3d_pb2'
  # @@protoc_insertion_point(class_scope:PrintRequest)
  })
_sym_db.RegisterMessage(PrintRequest)

PrintResponse = _reflection.GeneratedProtocolMessageType('PrintResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRINTRESPONSE,
  '__module__' : 'print_3d_pb2'
  # @@protoc_insertion_point(class_scope:PrintResponse)
  })
_sym_db.RegisterMessage(PrintResponse)



_PRINTER3D = _descriptor.ServiceDescriptor(
  name='Printer3D',
  full_name='Printer3D',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=158,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='Print',
    full_name='Printer3D.Print',
    index=0,
    containing_service=None,
    input_type=_PRINTREQUEST,
    output_type=_PRINTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRINTER3D)

DESCRIPTOR.services_by_name['Printer3D'] = _PRINTER3D

# @@protoc_insertion_point(module_scope)
