# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import print_3d_pb2 as print__3d__pb2


class Printer3DStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Print = channel.unary_unary(
        '/Printer3D/Print',
        request_serializer=print__3d__pb2.PrintRequest.SerializeToString,
        response_deserializer=print__3d__pb2.PrintResponse.FromString,
        )


class Printer3DServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Print(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Printer3DServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Print': grpc.unary_unary_rpc_method_handler(
          servicer.Print,
          request_deserializer=print__3d__pb2.PrintRequest.FromString,
          response_serializer=print__3d__pb2.PrintResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Printer3D', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
