# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: led_sign.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='led_sign.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0eled_sign.proto\"&\n\x0eLedSignRequest\x12\x14\n\x0cofficer_name\x18\x01 \x01(\t\"\"\n\x0fLedSignResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x9c\x01\n\rLedSignRecord\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nbrightness\x18\x02 \x01(\x05\x12\x14\n\x0cscroll_speed\x18\x03 \x01(\x05\x12\x18\n\x10\x62\x61\x63kground_color\x18\x04 \x01(\t\x12\x12\n\ntext_color\x18\x05 \x01(\t\x12\x14\n\x0c\x62order_color\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t2m\n\x07LedSign\x12.\n\x0bHealthCheck\x12\x0f.LedSignRequest\x1a\x0e.LedSignRecord\x12\x32\n\x0eUpdateSignText\x12\x0e.LedSignRecord\x1a\x10.LedSignResponseb\x06proto3'
)




_LEDSIGNREQUEST = _descriptor.Descriptor(
  name='LedSignRequest',
  full_name='LedSignRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='officer_name', full_name='LedSignRequest.officer_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=56,
)


_LEDSIGNRESPONSE = _descriptor.Descriptor(
  name='LedSignResponse',
  full_name='LedSignResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='LedSignResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=92,
)


_LEDSIGNRECORD = _descriptor.Descriptor(
  name='LedSignRecord',
  full_name='LedSignRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='LedSignRecord.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brightness', full_name='LedSignRecord.brightness', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scroll_speed', full_name='LedSignRecord.scroll_speed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='background_color', full_name='LedSignRecord.background_color', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_color', full_name='LedSignRecord.text_color', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='border_color', full_name='LedSignRecord.border_color', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='LedSignRecord.message', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=251,
)

DESCRIPTOR.message_types_by_name['LedSignRequest'] = _LEDSIGNREQUEST
DESCRIPTOR.message_types_by_name['LedSignResponse'] = _LEDSIGNRESPONSE
DESCRIPTOR.message_types_by_name['LedSignRecord'] = _LEDSIGNRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LedSignRequest = _reflection.GeneratedProtocolMessageType('LedSignRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEDSIGNREQUEST,
  '__module__' : 'led_sign_pb2'
  # @@protoc_insertion_point(class_scope:LedSignRequest)
  })
_sym_db.RegisterMessage(LedSignRequest)

LedSignResponse = _reflection.GeneratedProtocolMessageType('LedSignResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEDSIGNRESPONSE,
  '__module__' : 'led_sign_pb2'
  # @@protoc_insertion_point(class_scope:LedSignResponse)
  })
_sym_db.RegisterMessage(LedSignResponse)

LedSignRecord = _reflection.GeneratedProtocolMessageType('LedSignRecord', (_message.Message,), {
  'DESCRIPTOR' : _LEDSIGNRECORD,
  '__module__' : 'led_sign_pb2'
  # @@protoc_insertion_point(class_scope:LedSignRecord)
  })
_sym_db.RegisterMessage(LedSignRecord)



_LEDSIGN = _descriptor.ServiceDescriptor(
  name='LedSign',
  full_name='LedSign',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=253,
  serialized_end=362,
  methods=[
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='LedSign.HealthCheck',
    index=0,
    containing_service=None,
    input_type=_LEDSIGNREQUEST,
    output_type=_LEDSIGNRECORD,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateSignText',
    full_name='LedSign.UpdateSignText',
    index=1,
    containing_service=None,
    input_type=_LEDSIGNRECORD,
    output_type=_LEDSIGNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEDSIGN)

DESCRIPTOR.services_by_name['LedSign'] = _LEDSIGN

# @@protoc_insertion_point(module_scope)
