# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import print_pb2 as print__pb2


class PrinterStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrintPage = channel.unary_unary(
                '/Printer/PrintPage',
                request_serializer=print__pb2.PrintRequest.SerializeToString,
                response_deserializer=print__pb2.PrintResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/Printer/HealthCheck',
                request_serializer=print__pb2.HealthCheckUpRequest.SerializeToString,
                response_deserializer=print__pb2.PrinterHealthStatus.FromString,
                )


class PrinterServicer(object):
    """Missing associated documentation comment in .proto file"""

    def PrintPage(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrinterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrintPage': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintPage,
                    request_deserializer=print__pb2.PrintRequest.FromString,
                    response_serializer=print__pb2.PrintResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=print__pb2.HealthCheckUpRequest.FromString,
                    response_serializer=print__pb2.PrinterHealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Printer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Printer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def PrintPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Printer/PrintPage',
            print__pb2.PrintRequest.SerializeToString,
            print__pb2.PrintResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Printer/HealthCheck',
            print__pb2.HealthCheckUpRequest.SerializeToString,
            print__pb2.PrinterHealthStatus.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
