# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: print.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='print.proto',
  package='',

  serialized_pb=b'\n\x0bprint.proto\"\xa6\x01\n\x0cPrintRequest\x12\x0e\n\x06\x63opies\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12+\n\x07options\x18\x03 \x03(\x0b\x32\x1a.PrintRequest.OptionsEntry\x12\x14\n\x0c\x65ncoded_file\x18\x04 \x01(\x0c\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\rPrintResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x1bPrinterHealthCheckUpRequest\x12\x13\n\x0bmember_name\x18\x01 \x01(\t\"&\n\x13PrinterHealthStatus\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\x07Printer\x12*\n\tPrintPage\x12\r.PrintRequest\x1a\x0e.PrintResponse\x12\x41\n\x0bHealthCheck\x12\x1c.PrinterHealthCheckUpRequest\x1a\x14.PrinterHealthStatusb\x06proto3'
)




_PRINTREQUEST_OPTIONSENTRY = _descriptor.Descriptor(
  name='OptionsEntry',
  full_name='PrintRequest.OptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PrintRequest.OptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PrintRequest.OptionsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=182,
)

_PRINTREQUEST = _descriptor.Descriptor(
  name='PrintRequest',
  full_name='PrintRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='copies', full_name='PrintRequest.copies', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='PrintRequest.destination', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='PrintRequest.options', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoded_file', full_name='PrintRequest.encoded_file', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PRINTREQUEST_OPTIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=182,
)


_PRINTRESPONSE = _descriptor.Descriptor(
  name='PrintResponse',
  full_name='PrintResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='PrintResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=216,
)


_PRINTERHEALTHCHECKUPREQUEST = _descriptor.Descriptor(
  name='PrinterHealthCheckUpRequest',
  full_name='PrinterHealthCheckUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='member_name', full_name='PrinterHealthCheckUpRequest.member_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=268,
)


_PRINTERHEALTHSTATUS = _descriptor.Descriptor(
  name='PrinterHealthStatus',
  full_name='PrinterHealthStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='PrinterHealthStatus.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=308,
)

_PRINTREQUEST_OPTIONSENTRY.containing_type = _PRINTREQUEST
_PRINTREQUEST.fields_by_name['options'].message_type = _PRINTREQUEST_OPTIONSENTRY
DESCRIPTOR.message_types_by_name['PrintRequest'] = _PRINTREQUEST
DESCRIPTOR.message_types_by_name['PrintResponse'] = _PRINTRESPONSE
DESCRIPTOR.message_types_by_name['PrinterHealthCheckUpRequest'] = _PRINTERHEALTHCHECKUPREQUEST
DESCRIPTOR.message_types_by_name['PrinterHealthStatus'] = _PRINTERHEALTHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrintRequest = _reflection.GeneratedProtocolMessageType('PrintRequest', (_message.Message,), {

  'OptionsEntry' : _reflection.GeneratedProtocolMessageType('OptionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PRINTREQUEST_OPTIONSENTRY,
    '__module__' : 'print_pb2'
    # @@protoc_insertion_point(class_scope:PrintRequest.OptionsEntry)
    })
  ,
  'DESCRIPTOR' : _PRINTREQUEST,
  '__module__' : 'print_pb2'
  # @@protoc_insertion_point(class_scope:PrintRequest)
  })
_sym_db.RegisterMessage(PrintRequest)
_sym_db.RegisterMessage(PrintRequest.OptionsEntry)

PrintResponse = _reflection.GeneratedProtocolMessageType('PrintResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRINTRESPONSE,
  '__module__' : 'print_pb2'
  # @@protoc_insertion_point(class_scope:PrintResponse)
  })
_sym_db.RegisterMessage(PrintResponse)

PrinterHealthCheckUpRequest = _reflection.GeneratedProtocolMessageType('PrinterHealthCheckUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRINTERHEALTHCHECKUPREQUEST,
  '__module__' : 'print_pb2'
  # @@protoc_insertion_point(class_scope:PrinterHealthCheckUpRequest)
  })
_sym_db.RegisterMessage(PrinterHealthCheckUpRequest)

PrinterHealthStatus = _reflection.GeneratedProtocolMessageType('PrinterHealthStatus', (_message.Message,), {
  'DESCRIPTOR' : _PRINTERHEALTHSTATUS,
  '__module__' : 'print_pb2'
  # @@protoc_insertion_point(class_scope:PrinterHealthStatus)
  })
_sym_db.RegisterMessage(PrinterHealthStatus)


_PRINTREQUEST_OPTIONSENTRY._options = None

_PRINTER = _descriptor.ServiceDescriptor(
  name='Printer',
  full_name='Printer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=310,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='PrintPage',
    full_name='Printer.PrintPage',
    index=0,
    containing_service=None,
    input_type=_PRINTREQUEST,
    output_type=_PRINTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='Printer.HealthCheck',
    index=1,
    containing_service=None,
    input_type=_PRINTERHEALTHCHECKUPREQUEST,
    output_type=_PRINTERHEALTHSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRINTER)

DESCRIPTOR.services_by_name['Printer'] = _PRINTER

# @@protoc_insertion_point(module_scope)
