/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.FaceCoordinateRequest', null, global);
goog.exportSymbol('proto.FaceCoordinateResponse', null, global);
goog.exportSymbol('proto.FaceCoordinateResponse.Face', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FaceCoordinateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FaceCoordinateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.FaceCoordinateRequest.displayName = 'proto.FaceCoordinateRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FaceCoordinateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.FaceCoordinateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FaceCoordinateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FaceCoordinateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    faceimage: msg.getFaceimage_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FaceCoordinateRequest}
 */
proto.FaceCoordinateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FaceCoordinateRequest;
  return proto.FaceCoordinateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FaceCoordinateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FaceCoordinateRequest}
 */
proto.FaceCoordinateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFaceimage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FaceCoordinateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FaceCoordinateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FaceCoordinateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FaceCoordinateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFaceimage_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes faceImage = 1;
 * @return {!(string|Uint8Array)}
 */
proto.FaceCoordinateRequest.prototype.getFaceimage = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes faceImage = 1;
 * This is a type-conversion wrapper around `getFaceimage()`
 * @return {string}
 */
proto.FaceCoordinateRequest.prototype.getFaceimage_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFaceimage()));
};


/**
 * optional bytes faceImage = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFaceimage()`
 * @return {!Uint8Array}
 */
proto.FaceCoordinateRequest.prototype.getFaceimage_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFaceimage()));
};


/** @param {!(string|Uint8Array)} value */
proto.FaceCoordinateRequest.prototype.setFaceimage = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FaceCoordinateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.FaceCoordinateResponse.repeatedFields_, null);
};
goog.inherits(proto.FaceCoordinateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.FaceCoordinateResponse.displayName = 'proto.FaceCoordinateResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.FaceCoordinateResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FaceCoordinateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.FaceCoordinateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FaceCoordinateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FaceCoordinateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    facesList: jspb.Message.toObjectList(msg.getFacesList(),
    proto.FaceCoordinateResponse.Face.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FaceCoordinateResponse}
 */
proto.FaceCoordinateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FaceCoordinateResponse;
  return proto.FaceCoordinateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FaceCoordinateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FaceCoordinateResponse}
 */
proto.FaceCoordinateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.FaceCoordinateResponse.Face;
      reader.readMessage(value,proto.FaceCoordinateResponse.Face.deserializeBinaryFromReader);
      msg.addFaces(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FaceCoordinateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FaceCoordinateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FaceCoordinateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FaceCoordinateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFacesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.FaceCoordinateResponse.Face.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FaceCoordinateResponse.Face = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FaceCoordinateResponse.Face, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.FaceCoordinateResponse.Face.displayName = 'proto.FaceCoordinateResponse.Face';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FaceCoordinateResponse.Face.prototype.toObject = function(opt_includeInstance) {
  return proto.FaceCoordinateResponse.Face.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FaceCoordinateResponse.Face} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FaceCoordinateResponse.Face.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tlx: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    tly: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    brx: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    bry: +jspb.Message.getFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FaceCoordinateResponse.Face}
 */
proto.FaceCoordinateResponse.Face.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FaceCoordinateResponse.Face;
  return proto.FaceCoordinateResponse.Face.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FaceCoordinateResponse.Face} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FaceCoordinateResponse.Face}
 */
proto.FaceCoordinateResponse.Face.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTlx(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTly(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBrx(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FaceCoordinateResponse.Face.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FaceCoordinateResponse.Face.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FaceCoordinateResponse.Face} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FaceCoordinateResponse.Face.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTlx();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getTly();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getBrx();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getBry();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.FaceCoordinateResponse.Face.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.FaceCoordinateResponse.Face.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double tlx = 2;
 * @return {number}
 */
proto.FaceCoordinateResponse.Face.prototype.getTlx = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.FaceCoordinateResponse.Face.prototype.setTlx = function(value) {
  jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double tly = 3;
 * @return {number}
 */
proto.FaceCoordinateResponse.Face.prototype.getTly = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.FaceCoordinateResponse.Face.prototype.setTly = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double brx = 4;
 * @return {number}
 */
proto.FaceCoordinateResponse.Face.prototype.getBrx = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.FaceCoordinateResponse.Face.prototype.setBrx = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double bry = 5;
 * @return {number}
 */
proto.FaceCoordinateResponse.Face.prototype.getBry = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.FaceCoordinateResponse.Face.prototype.setBry = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * repeated Face faces = 1;
 * @return {!Array<!proto.FaceCoordinateResponse.Face>}
 */
proto.FaceCoordinateResponse.prototype.getFacesList = function() {
  return /** @type{!Array<!proto.FaceCoordinateResponse.Face>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.FaceCoordinateResponse.Face, 1));
};


/** @param {!Array<!proto.FaceCoordinateResponse.Face>} value */
proto.FaceCoordinateResponse.prototype.setFacesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.FaceCoordinateResponse.Face=} opt_value
 * @param {number=} opt_index
 * @return {!proto.FaceCoordinateResponse.Face}
 */
proto.FaceCoordinateResponse.prototype.addFaces = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.FaceCoordinateResponse.Face, opt_index);
};


proto.FaceCoordinateResponse.prototype.clearFacesList = function() {
  this.setFacesList([]);
};


goog.object.extend(exports, proto);
