# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import aws_rekognition_pb2 as aws__rekognition__pb2


class FaceImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestFaceCoordinate = channel.unary_unary(
                '/FaceImage/RequestFaceCoordinate',
                request_serializer=aws__rekognition__pb2.FaceCoordinateRequest.SerializeToString,
                response_deserializer=aws__rekognition__pb2.FaceCoordinateResponse.FromString,
                )


class FaceImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestFaceCoordinate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestFaceCoordinate': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFaceCoordinate,
                    request_deserializer=aws__rekognition__pb2.FaceCoordinateRequest.FromString,
                    response_serializer=aws__rekognition__pb2.FaceCoordinateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FaceImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestFaceCoordinate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceImage/RequestFaceCoordinate',
            aws__rekognition__pb2.FaceCoordinateRequest.SerializeToString,
            aws__rekognition__pb2.FaceCoordinateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
